### PR TITLE
feat: add a mutationObserver to reload when some valid attributes changes

### PR DESCRIPTION
**Pull request by iam-frankqiu**
Added a MutationObserver to some valid attributes like data-src, when data-src changed, reload

### CODE REVIEW

**Comment by ApoorvSaxena** [comment]
@frankqiu0219 Please add this information in README and Demo file with an example as well. This will be a great addition as functionality.

**Comment by frankqiu0219** [comment]
> @frankqiu0219 Please add this information in README and Demo file with an example as well. This will be a great addition as functionality.
Thank you. I will do it quickly.

**Comment by ApoorvSaxena** [comment]
@iam-frankqiu please fix the conflicting issues, also, a configuration should allow to disable the use of Mutation Observer, and it shouldn't be enabled by default, considering the performance implications

**Comment by ApoorvSaxena** [comment]
@iam-frankqiu any updates on this?

**Comment by iam-frankqiu** [comment]
> @iam-frankqiu any updates on this?

yeah, sorry for the late reply, I was pretty busy, I will update this repository soon.

**Comment by ApoorvSaxena** [comment]
@iam-frankqiu please add `coverage` folder in `.gitignore`

**Comment by iam-frankqiu** [comment]
> @iam-frankqiu please add `coverage` folder in `.gitignore`

well. It's done.

**Pull request merged**
