### PR TITLE
Picture tag can now handle an inside img tag if it exists

### PR DESCRIPTION
**Pull request by srogier**
This PR will allow to picture tag like this.

```
<picture
    class="lozad"
    data-iesrc="https://example.org/foo.jpg">
    <source type="image/webp"
            data-srcset="https://example.org/foo.webp"
            class="lozad" />
    <source type="image/jpeg"
            data-srcset="https://example.org/foo.jpg"
            class="lozad"/>
    <img src="data:image/jpeg;base64,/some_lqip_in_base_64==" />
</picture>
```

With this code, I can use a lazy-loaded `<picture>` tag, with an LQIP and delegate the lazy-load to the `<source>` tags inside the `<picture>` tag

### CODE REVIEW

**Comment by nickreese** [comment]
Would love to see this merged in. Thank you for your work. :)

**Comment by MBehtemam** [comment]
what happen for this PR , I think it's useful to have this in library.

**Comment by nickreese** [comment]
Checking in on this again. Lozad is our preferred solution but we need LQIP support.

**Comment by srogier** [comment]
Yes, it's too bad this PR isn't merged.

If that can reassure you, this code runs on prod since last february without any issues.

**Comment by ApoorvSaxena** [comment]
@srogier will be great if you can get the following done, will get this merged ASAP:
* update README.md with feature implementation
* build and update dist files to resolve their conflict

Bonus points to accompany test cases with PR 💯

**Comment by srogier** [comment]
PR is now update from master @ApoorvSaxena with a new build

I add some documentation.
I also tried bonus points with testing, but I wasn't very inspired

**Pull request merged**
