### PR TITLE
Responsive image support + Misc

### PR DESCRIPTION
**Pull request by ApoorvSaxena**
- feature addition https://github.com/ApoorvSaxena/lozad.js/issues/28
- compressed banner and images used in demo

### CODE REVIEW

**Comment by ApoorvSaxena** [comment]
@thiamsantos @stephenkingsley @lptn @bfred-it please review

**Comment by stephenkingsley** [comment]
@ApoorvSaxena I pick it up! I will review in today.

**Comment by stephenkingsley** [comment]
I think is cool!

**Comment by stephenkingsley** [comment]
+1

**Comment by thiamsantos** [comment]
Awesome!!!!!

**Pull request merged**
