### PR TITLE
Fixing the failing build 

### LINKED ISSUE #200: Fix failing build

### PR DESCRIPTION
**Pull request by osmarpetry**
Resolves #200

### CODE REVIEW

**Comment by draconteus** [comment]
Still failing, because a sub-dependency, brotli-size no longer supports node < 10.16.0

**Comment by osmarpetry** [comment]
Wow, this is new. I try to fix tonight

**Comment by osmarpetry** [comment]
@draconteus do you have any idea what could be causing the errors in the Travis? It's working on my local machine

**Comment by draconteus** [comment]
For the first build, there is this line:
`error brotli-size@4.0.0: The engine "node" is incompatible with this module. Expected version ">= 10.16.0". Got "8.16.2"`

For the next builds, I'm not sure. I would start to check if:
- local node version === travis node version
- local npm version ===  travis npm version
- local yarn version ===  travis yarn version
- package-lockfile is generated with the correct npm
- yarn.lock is generated with the correct yarn
- there are no other package that does not support never version of node

**Comment by osmarpetry** [comment]
I don't know what is happening wrong, the problem probably is in `src/lozad.js` line 22. Maybe @Ishaan28malik can help us

**Comment by Ishaan28malik** [comment]
Yeah let me give it a try.

**Comment by ApoorvSaxena** [comment]
It's been fixed by @razi-ed reference https://github.com/ApoorvSaxena/lozad.js/pull/208/

**Pull request closed without merging**
